# * Common configuration
x-madsci-service: &madsci-service
  image: ghcr.io/ad-sdl/madsci:v0.4.1
  environment:
    - USER_ID=${USER_ID:-1000}
    - GROUP_ID=${GROUP_ID:-1000}
  network_mode: host
  env_file:
    - ../.env
  volumes:
    - ${REPO_PATH:-.}/:/home/madsci/badlab_sdl
    - ${REPO_PATH:-.}/.madsci:/home/madsci/.madsci
  restart: unless-stopped

services:

  peeler_potato:
    <<: *madsci-service
    container_name: peeler_potato
    image: ghcr.io/ad-sdl/brooks_xpeel_module:dev
    privileged: true
    volumes:
      - ../nodes:/home/madsci/nodes
      - /dev:/dev
    command: python -m peeler_rest_node --definition nodes/peeler_potato.node.yaml

  sealer_harp:
    <<: *madsci-service
    container_name: sealer_harp
    image: ghcr.io/ad-sdl/a4s_sealer_module:dev
    privileged: true
    volumes:
      - ../nodes:/home/madsci/nodes
      - /dev:/dev
    command: python -m sealer_rest_node --definition nodes/sealer_harp.node.yaml
