# * Common configuration
x-madsci-service: &madsci-service
  image: ghcr.io/ad-sdl/madsci:v0.4.2
  environment:
    - USER_ID=${USER_ID:-1000}
    - GROUP_ID=${GROUP_ID:-1000}
  network_mode: host
  env_file:
    - ../.env
  volumes:
    - ../:/home/madsci/rapid350_sdl
    - ../.madsci:/home/madsci/.madsci
  restart: unless-stopped

services:

  platecrane_poly:
    <<: *madsci-service
    container_name: platecrane_poly
    image: ghcr.io/ad-sdl/hudson_platecrane_module
    privileged: true
    environment:
      - NODE_URL=http://potts.cels.anl.gov:2000/
      - NODE_DEVICE=/dev/ttyUSB2
      - NODE_DEFINITION=nodes/platecrane_poly.node.yaml
    volumes:
      - ../nodes:/home/madsci/nodes
      - /dev:/dev
    command: python hudson_platecrane_module/src/hudson_platecrane_node.py

  peeler_potato:
    <<: *madsci-service
    container_name: peeler_potato
    image: ghcr.io/ad-sdl/brooks_xpeel_module
    privileged: true
    environment:
      - NODE_URL=http://potts.cels.anl.gov:2001/
      - NODE_DEVICE_PORT=/dev/ttyUSB4
      - NODE_DEFINITION=nodes/peeler_potato.node.yaml
    volumes:
      - ../nodes:/home/madsci/nodes
      - /dev:/dev
    command: python -m peeler_rest_node

  sealer_harp:
    <<: *madsci-service
    container_name: sealer_harp
    image: ghcr.io/ad-sdl/a4s_sealer_module
    privileged: true
    environment:
      - NODE_URL=http://potts.cels.anl.gov:2002/
      - NODE_DEVICE_PATH=/dev/ttyUSB6
      - NODE_DEFINITION=nodes/sealer_harp.node.yaml
    volumes:
      - ../nodes:/home/madsci/nodes
      - /dev:/dev

  liconic_lisa:
    <<: *madsci-service
    container_name: liconic_lisa
    image: ghcr.io/ad-sdl/liconic_module
    privileged: true
    environment:
      - NODE_URL=http://potts.cels.anl.gov:2003/
      - NODE_DEVICE=/dev/ttyUSB0
      - NODE_DEFINITION=nodes/liconic_lisa.node.yaml
    volumes:
      - ../nodes:/home/madsci/nodes
      - /dev:/dev
      - ../.madsci:/home/madsci/.madsci
